name: CI for Selenium Python Project

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12.3
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.3"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - uses: actions/checkout@v3
        if: success() || failure()
      - run: |
          cd tests
          mkdir -p reports
          pytest test_e2e_demo_ecom_store.py --browser=chrome --html=reports/reports.html
          chmod 777  \selenium-python-project\tests\reports
          

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=tests/reports/" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-report
          path: ${{ steps.results.outputs.artifactPath }}