name: CI for Selenium Python Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.3
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: '130.0.6723.44'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install webdriver-manager

    - name: Run tests
      env:
        DISPLAY: ":99"  # Needed for headless mode on Linux
      run: |
        pytest tests/
